import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'orbit-hosted-test-')),origin='http://127.0.0.1:18877';let child;
const request=async(route,input,session)=>{const r=await fetch(origin+route,{method:input?'POST':'GET',headers:{...(input?{'Content-Type':'application/json',Origin:origin}:{}),...(session?{Cookie:session.cookie,'X-App-Token':session.csrf}: {})},...(input?{body:JSON.stringify(input)}:{})});return {status:r.status,value:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
test.before(async()=>{child=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:'18877',APP_URL:origin,JOB_AGENT_DATA:dir,NODE_ENV:'test',VAULT_KEY:'a'.repeat(64)},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Hosted test startup timeout')),30000);child.stdout.on('data',v=>{if(String(v).includes('Job Outreach Agent')){clearTimeout(timer);resolve();}});child.once('error',reject);});});
async function account(handle){const r=await request('/api/auth/register',{handle,password:'A long test password 123'});assert.equal(r.status,200);const s={cookie:r.cookie};const me=await request('/api/auth/me',null,s);s.csrf=me.value.csrfToken;return s;}
test('public service rejects anonymous state and isolates users and secrets',async()=>{assert.equal((await request('/api/state')).status,401);const alice=await account('alice'),bob=await account('bob');assert.equal((await request('/api/profile',{name:'Alice',roles:'Engineer'},alice)).status,200);assert.equal((await request('/api/state',null,bob)).value.profile.name,'');assert.equal((await request('/api/state',null,alice)).value.profile.name,'Alice');assert.equal((await request('/api/api-key',{key:'sk-testONLY_NOT_A_REAL_KEY',model:'gpt-6-luna'},alice)).status,200);const a=(await request('/api/state',null,alice)).value,b=(await request('/api/state',null,bob)).value;assert.equal(a.connection.apiConfigured,true);assert.equal(b.connection.apiConfigured,false);assert.equal(a.connection.model,'gpt-6-luna');assert.ok(!JSON.stringify(a).includes('sk-test'));const files=fs.readdirSync(path.join(dir,'users')).map(id=>path.join(dir,'users',id,'vault.json')).filter(fs.existsSync);assert.ok(files.length);assert.ok(files.every(file=>!fs.readFileSync(file,'utf8').includes('sk-test')));assert.equal((await request('/api/profile',{name:'Evil',roles:'Engineer'},{cookie:bob.cookie,csrf:alice.csrf})).status,400);});
test('chat task persists and completes a local stats request; retries reuse the same task',async()=>{const user=await account('charlie'),input={message:'Show my stats',requestId:'test-request'};const first=await request('/api/chat',input,user);assert.equal(first.status,200);const second=await request('/api/chat',input,user);assert.equal(second.value.result.taskId,first.value.result.taskId);let s;for(let i=0;i<20;i++){s=(await request('/api/state',null,user)).value;if(s.tasks?.[0]?.status==='completed')break;await new Promise(resolve=>setTimeout(resolve,50));}assert.equal(s.tasks[0].status,'completed');assert.equal(s.chat.at(-1).actions[0].result.sent,0);assert.equal((await request('/api/auth/logout',{},user)).status,200);assert.equal((await request('/api/state',null,user)).status,401);});
test.after(async()=>{if(child&&child.exitCode===null)await new Promise(resolve=>{child.once('exit',resolve);child.kill();});fs.rmSync(dir,{recursive:true,force:true});});
test('external schedule endpoint refuses requests without its server secret',async()=>{assert.equal((await request('/internal/schedule',{})).status,401);const r=await fetch(origin+'/internal/schedule',{method:'POST',headers:{Authorization:'Bearer guessed-secret'}});assert.equal(r.status,401);});
