import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {DATA} from './config.mjs';

// Private encrypted object snapshots. One app instance must own this namespace.
const enabled=()=>Boolean(process.env.STORAGE_GATEWAY_URL || process.env.SUPABASE_URL);
let tail=Promise.resolve(),generation=0,known=new Map();
const digest=b=>crypto.createHash('sha256').update(b).digest('hex');
function key(){if(!/^[a-f0-9]{64}$/i.test(process.env.VAULT_KEY||''))throw Error('Cloud storage requires a stable 64-hex VAULT_KEY.');return Buffer.from(process.env.VAULT_KEY,'hex');}
export function encryptFile(bytes){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv),data=Buffer.concat([c.update(bytes),c.final()]);return Buffer.concat([Buffer.from('ORB1'),iv,c.getAuthTag(),data]);}
export function decryptFile(bytes){if(bytes.subarray(0,4).toString()!=='ORB1')throw Error('Invalid encrypted cloud object.');const c=crypto.createDecipheriv('aes-256-gcm',key(),bytes.subarray(4,16));c.setAuthTag(bytes.subarray(16,32));return Buffer.concat([c.update(bytes.subarray(32)),c.final()]);}
export function safeFile(name){if(typeof name!=='string'||!name||name.includes('\\')||name.split('/').some(x=>!x||x==='.'||x==='..')||path.isAbsolute(name))throw Error('Invalid cloud file path.');return path.join(DATA,...name.split('/'));}
async function request(name,method='GET',bytes){
if(process.env.STORAGE_GATEWAY_URL){
 const url=new URL(process.env.STORAGE_GATEWAY_URL);
 if(url.protocol!=='https:'||!url.hostname.endsWith('.supabase.co')||url.pathname!=='/functions/v1/orbit-storage'||url.search||url.hash||url.username||url.password||url.port)throw Error('Invalid storage gateway address.');
 if(!/^[a-f0-9]{64}$/.test(process.env.STORAGE_GATEWAY_TOKEN||''))throw Error('Configure the Orbit-only storage token.');
 url.searchParams.set('object',name);
 const r=await fetch(url,{method,headers:{'x-orbit-token':process.env.STORAGE_GATEWAY_TOKEN,'Content-Type':'application/octet-stream'},body:bytes,redirect:'error',signal:AbortSignal.timeout(30000)});
 if(!r.ok){const error=Error('Orbit storage gateway failed ('+r.status+').');error.notFound=r.status===404;throw error;}return r;
}
const base=process.env.SUPABASE_URL?.replace(/\/$/,''),secret=process.env.SUPABASE_SECRET_KEY,bucket=process.env.SUPABASE_BUCKET||'orbit-private';if(!secret||!/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(base||''))throw Error('Configure SUPABASE_URL and server-only SUPABASE_SECRET_KEY.');const headers={apikey:secret};if(!secret.startsWith('sb_secret_'))headers.Authorization='Bearer '+secret;if(bytes){headers['Content-Type']='application/octet-stream';headers['x-upsert']='true';}let endpoint='/'+name.split('/').map(encodeURIComponent).join('/');if(method==='DELETE'){endpoint='';headers['Content-Type']='application/json';bytes=JSON.stringify({prefixes:[name]});}const r=await fetch(base+'/storage/v1/object/'+encodeURIComponent(bucket)+endpoint,{method,headers,body:bytes,signal:AbortSignal.timeout(30000)});if(!r.ok){const info=await r.json().catch(()=>({})),error=Error('Private storage request failed ('+r.status+'). Check the bucket, server key and free-tier quota.');error.notFound=r.status===404||String(info.statusCode)==='404'||info.error==='not_found';throw error;}return r;}
function files(dir=DATA,prefix=''){let out=[];for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(e.name.endsWith('.tmp')||e.name==='.vault-key')continue;const name=prefix+e.name;if(e.isDirectory())out.push(...files(path.join(dir,e.name),name+'/'));else if(e.isFile())out.push([name,fs.readFileSync(path.join(dir,e.name))]);}return out;}
export async function restoreCloud(){if(!enabled())return;let response;try{response=await request('manifest');}catch(e){if(!e.notFound)throw e;await request('manifest','POST',encryptFile(Buffer.from(JSON.stringify({generation:0,files:[]}))));return;}const manifest=JSON.parse(decryptFile(Buffer.from(await response.arrayBuffer())));if(!Array.isArray(manifest.files))throw Error('Invalid cloud manifest.');generation=manifest.generation||0;known=new Map();for(const item of manifest.files){const target=safeFile(item.name);if(!/^[a-f0-9]{64}$/.test(item.hash)||!/^versions\/[a-f0-9-]+$/.test(item.object))throw Error('Invalid cloud manifest entry.');const r=await request(item.object),bytes=decryptFile(Buffer.from(await r.arrayBuffer()));if(digest(bytes)!==item.hash)throw Error('Cloud object integrity check failed.');fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,bytes,{mode:0o600});known.set(item.name,item);}}
export function flushCloud(){if(!enabled())return Promise.resolve();const next=tail.catch(()=>{}).then(async()=>{const entries=files(),updated=new Map();let changed=false;for(const [name,bytes] of entries){const hash=digest(bytes),old=known.get(name);if(old?.hash===hash){updated.set(name,old);continue;}const object='versions/'+crypto.randomUUID();await request(object,'POST',encryptFile(bytes));updated.set(name,{name,hash,object});changed=true;}if(!changed&&updated.size===known.size)return;const manifest={generation:generation+1,files:[...updated.values()]};await request('manifest','POST',encryptFile(Buffer.from(JSON.stringify(manifest))));const retired=[...known.values()].filter(x=>updated.get(x.name)?.object!==x.object);known=updated;generation++;for(const entry of retired){try{await request(entry.object,'DELETE');}catch{console.error('Cloud object cleanup pending; review storage usage.');}}});tail=next;return next;}
