// Fetch fixed public feeds only. No applicant data is sent to job boards.
let cached,until=0;
const plain=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
export async function candidates(data,{fetcher=fetch}={}){
 if(!cached||Date.now()>until){const r=await fetcher('https://www.arbeitnow.com/api/job-board-api',{signal:AbortSignal.timeout(20000),redirect:'error'});if(!r.ok)throw Error('Free job feed unavailable. Try again later.');const body=await r.json();if(!Array.isArray(body.data))throw Error('Invalid job feed.');cached=body.data.filter(j=>typeof j.url==='string'&&j.url.startsWith('https://www.arbeitnow.com/jobs/')&&Number(j.created_at)*1000>Date.now()-60*86400000).map(j=>({company:plain(j.company_name),title:plain(j.title),location:plain(j.location)+(j.remote?' (remote)':''),url:j.url,description:plain(j.description).slice(0,1800),source:'Arbeitnow',checkedAt:new Date().toISOString()}));until=Date.now()+3600000;}
 const words=String(data.profile?.roles||'').toLowerCase().match(/[a-z0-9+#.]{3,}/g)||[],known=new Set(data.knownJobURLs||[]);
 return cached.filter(j=>!known.has(j.url)).map(j=>({...j,weight:words.reduce((n,w)=>n+(j.title.toLowerCase().includes(w)?3:0)+(j.description.toLowerCase().includes(w)?1:0),0)})).filter(j=>j.weight>0).sort((a,b)=>b.weight-a.weight).slice(0,16).map((j,i)=>({...j,id:'feed-'+i}));
}
export async function searchFeed(data,infer){const list=await candidates(data);if(!list.length)return {jobs:[]};const result=await infer('Select relevant jobs from the supplied public feed for the applicant. Respect location and eligibility; return fewer or none when unsuitable. Return JSON {"jobs":[{"id":"supplied feed ID","score":0,"reasons":["supported fit"],"gaps":["missing requirement"]}]}. Never invent a job or change its ID. Scores 0..100.',{profile:data.profile,documents:data.documents,jobs:list});if(!Array.isArray(result.jobs))throw Error('Invalid local job matching result.');const seen=new Set();return {jobs:result.jobs.flatMap(x=>{const j=list.find(j=>j.id===x.id);if(!j||seen.has(j.id))return [];seen.add(j.id);return [{company:j.company,title:j.title,location:j.location,url:j.url,description:j.description,score:Math.max(0,Math.min(100,Number(x.score)||0)),reasons:Array.isArray(x.reasons)?x.reasons.map(String):[],gaps:Array.isArray(x.gaps)?x.gaps.map(String):[],contactEmail:'',contactSource:'',evidence:'Arbeitnow feed: '+j.title+' — '+j.company+'. Listed when fetched; confirm current availability on the linked listing.',checkedAt:j.checkedAt}];}).slice(0,Math.min(30,data.requestedCount||10))};}
